/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrucksRouteImport } from './routes/trucks'
import { Route as TrashRouteImport } from './routes/trash'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as DriversRouteImport } from './routes/drivers'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ConsignorsRouteImport } from './routes/consignors'
import { Route as ConsignmentsRouteImport } from './routes/consignments'
import { Route as ConsigneesRouteImport } from './routes/consignees'
import { Route as AuditLogRouteImport } from './routes/audit-log'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConsignmentsIndexRouteImport } from './routes/consignments.index'
import { Route as DispatchNewRouteImport } from './routes/dispatch.new'
import { Route as ConsignmentsIdRouteImport } from './routes/consignments.$id'

const TrucksRoute = TrucksRouteImport.update({
  id: '/trucks',
  path: '/trucks',
  getParentRoute: () => rootRouteImport,
} as any)
const TrashRoute = TrashRouteImport.update({
  id: '/trash',
  path: '/trash',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const DriversRoute = DriversRouteImport.update({
  id: '/drivers',
  path: '/drivers',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsignorsRoute = ConsignorsRouteImport.update({
  id: '/consignors',
  path: '/consignors',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsignmentsRoute = ConsignmentsRouteImport.update({
  id: '/consignments',
  path: '/consignments',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsigneesRoute = ConsigneesRouteImport.update({
  id: '/consignees',
  path: '/consignees',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditLogRoute = AuditLogRouteImport.update({
  id: '/audit-log',
  path: '/audit-log',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsignmentsIndexRoute = ConsignmentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ConsignmentsRoute,
} as any)
const DispatchNewRoute = DispatchNewRouteImport.update({
  id: '/dispatch/new',
  path: '/dispatch/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsignmentsIdRoute = ConsignmentsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ConsignmentsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audit-log': typeof AuditLogRoute
  '/consignees': typeof ConsigneesRoute
  '/consignments': typeof ConsignmentsRouteWithChildren
  '/consignors': typeof ConsignorsRoute
  '/dashboard': typeof DashboardRoute
  '/drivers': typeof DriversRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/trash': typeof TrashRoute
  '/trucks': typeof TrucksRoute
  '/consignments/$id': typeof ConsignmentsIdRoute
  '/dispatch/new': typeof DispatchNewRoute
  '/consignments/': typeof ConsignmentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audit-log': typeof AuditLogRoute
  '/consignees': typeof ConsigneesRoute
  '/consignors': typeof ConsignorsRoute
  '/dashboard': typeof DashboardRoute
  '/drivers': typeof DriversRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/trash': typeof TrashRoute
  '/trucks': typeof TrucksRoute
  '/consignments/$id': typeof ConsignmentsIdRoute
  '/dispatch/new': typeof DispatchNewRoute
  '/consignments': typeof ConsignmentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/audit-log': typeof AuditLogRoute
  '/consignees': typeof ConsigneesRoute
  '/consignments': typeof ConsignmentsRouteWithChildren
  '/consignors': typeof ConsignorsRoute
  '/dashboard': typeof DashboardRoute
  '/drivers': typeof DriversRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/trash': typeof TrashRoute
  '/trucks': typeof TrucksRoute
  '/consignments/$id': typeof ConsignmentsIdRoute
  '/dispatch/new': typeof DispatchNewRoute
  '/consignments/': typeof ConsignmentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/audit-log'
    | '/consignees'
    | '/consignments'
    | '/consignors'
    | '/dashboard'
    | '/drivers'
    | '/reports'
    | '/settings'
    | '/trash'
    | '/trucks'
    | '/consignments/$id'
    | '/dispatch/new'
    | '/consignments/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/audit-log'
    | '/consignees'
    | '/consignors'
    | '/dashboard'
    | '/drivers'
    | '/reports'
    | '/settings'
    | '/trash'
    | '/trucks'
    | '/consignments/$id'
    | '/dispatch/new'
    | '/consignments'
  id:
    | '__root__'
    | '/'
    | '/audit-log'
    | '/consignees'
    | '/consignments'
    | '/consignors'
    | '/dashboard'
    | '/drivers'
    | '/reports'
    | '/settings'
    | '/trash'
    | '/trucks'
    | '/consignments/$id'
    | '/dispatch/new'
    | '/consignments/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuditLogRoute: typeof AuditLogRoute
  ConsigneesRoute: typeof ConsigneesRoute
  ConsignmentsRoute: typeof ConsignmentsRouteWithChildren
  ConsignorsRoute: typeof ConsignorsRoute
  DashboardRoute: typeof DashboardRoute
  DriversRoute: typeof DriversRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  TrashRoute: typeof TrashRoute
  TrucksRoute: typeof TrucksRoute
  DispatchNewRoute: typeof DispatchNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trucks': {
      id: '/trucks'
      path: '/trucks'
      fullPath: '/trucks'
      preLoaderRoute: typeof TrucksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trash': {
      id: '/trash'
      path: '/trash'
      fullPath: '/trash'
      preLoaderRoute: typeof TrashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drivers': {
      id: '/drivers'
      path: '/drivers'
      fullPath: '/drivers'
      preLoaderRoute: typeof DriversRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consignors': {
      id: '/consignors'
      path: '/consignors'
      fullPath: '/consignors'
      preLoaderRoute: typeof ConsignorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consignments': {
      id: '/consignments'
      path: '/consignments'
      fullPath: '/consignments'
      preLoaderRoute: typeof ConsignmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consignees': {
      id: '/consignees'
      path: '/consignees'
      fullPath: '/consignees'
      preLoaderRoute: typeof ConsigneesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit-log': {
      id: '/audit-log'
      path: '/audit-log'
      fullPath: '/audit-log'
      preLoaderRoute: typeof AuditLogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consignments/': {
      id: '/consignments/'
      path: '/'
      fullPath: '/consignments/'
      preLoaderRoute: typeof ConsignmentsIndexRouteImport
      parentRoute: typeof ConsignmentsRoute
    }
    '/dispatch/new': {
      id: '/dispatch/new'
      path: '/dispatch/new'
      fullPath: '/dispatch/new'
      preLoaderRoute: typeof DispatchNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consignments/$id': {
      id: '/consignments/$id'
      path: '/$id'
      fullPath: '/consignments/$id'
      preLoaderRoute: typeof ConsignmentsIdRouteImport
      parentRoute: typeof ConsignmentsRoute
    }
  }
}

interface ConsignmentsRouteChildren {
  ConsignmentsIdRoute: typeof ConsignmentsIdRoute
  ConsignmentsIndexRoute: typeof ConsignmentsIndexRoute
}

const ConsignmentsRouteChildren: ConsignmentsRouteChildren = {
  ConsignmentsIdRoute: ConsignmentsIdRoute,
  ConsignmentsIndexRoute: ConsignmentsIndexRoute,
}

const ConsignmentsRouteWithChildren = ConsignmentsRoute._addFileChildren(
  ConsignmentsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuditLogRoute: AuditLogRoute,
  ConsigneesRoute: ConsigneesRoute,
  ConsignmentsRoute: ConsignmentsRouteWithChildren,
  ConsignorsRoute: ConsignorsRoute,
  DashboardRoute: DashboardRoute,
  DriversRoute: DriversRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  TrashRoute: TrashRoute,
  TrucksRoute: TrucksRoute,
  DispatchNewRoute: DispatchNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
